name = Ilot public layout
description = a 2 column layout website
preview = preview.png
template = onecolumn-layout

; Regions
regions[header] = Header
regions[content] = Content
regions[services] = Services
regions[map-block1]     = Map-block1
regions[map-block2]     = Map-block2
regions[footer]     = Footer
regions[off]        = Off Canvas

; Stylesheets
stylesheets[all][] = css/layouts/public/onecolumn.layout.css
stylesheets[all][] = css/layouts/public/onecolumn.layout.no-query.css

; Scripts
scripts[] = layouts/onepage/js/onecolumn.layout.behaviours.js
